src/OC/PlatformBundle/Entity/Image.php
<?php
// src/OC/PlatformBundle/Entity/Image

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * @ORM\Entity(repositoryClass="OC\PlatformBundle\Entity\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

	
	private $file;
	
	// Attribut pour stocker temporairement le nom du fichier
	private $tempFilename;
	
	
	public function getFile()
	{
	  return $this->file;
	}
	
	// On modifie le setter de File,pour prendre en compte l'upload d'un fichier lorqu'il en exite déja un autre
	public function setFile(UploadedFile $file = null)
	{
	  $this->file = $file;
	  
	  //On vérifie si on avait déja un fichier pour cette entité
	  if(null !== $this->url) {
	    $this->tempFilename = $this->url;
		
		// On réinitialise les valeurs des attributs 'url' et 'alt'
		$this->url = null;
		$this->alt = null;		
	  }
	}
	
	/**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
	
	
	/**
	* @ORM\PrePersist()
	* @ORM\PreUpdate()
	*/
	public function preUpload()
	{
	  // Si il n'y a pas de fichier (Champ facultatif)
	  if(null === $this->file) {
	    return ;
	  }
	  
      // Le nom du fichier est son id, on doit juste stocker également son extension
      // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
	  $this->url = $this->file->guessExtension();
	  
	  // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
	  $this->alt = $this->file->getClientOriginalName();	
	}
	
    /**
    * @ORM\PostPersist()
    * @ORM\PostUpdate()
    */	
	public function upload() 
	{
	  // Si il n'y a pas de fichier (champs facultatif), on ne fait rien
	  if(null == $this->file) {
	   return;
	  }
	  
	  // Si on avait un ancien fichier, on le supprime
	  if(null !== $this->tempFilename) {
	    $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
		if(file_exists($oldFile)) {
		  unlink($oldFile);
		}
	  }
	  
	  // On déplace le fichier envoyé dans le repertoire de notre choix
	  $this->file->move(
	    $this->getUploadRootDir(), // Répertoire de destination
	    $this->id.'.'.$this->url   // Nom du fichier a crée, ici "id.extension"
	  );
	}
	
	/**
	* @ORM\PreRemove
	*/
	public function preRemoveUpload() 
	{
	  // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
	  $this->tempFilename = $this->getUploadRootDir.'/'.$this->id.'.'.$this->url;
	}

	/**
	* @ORM\PostRemove
	*/
	public function removeUpload(){
	  // En "PostRemove" on n'a pas accès à l'id, on utilise le nom sauvegardé
	  if(file_exists($this->tempFilename)) {
	    unlink($this->tempFilename);
	  }
	}
	
	public function getUploadDir()
	{
	 // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
	  return 'uploads/img';
	}
	
	public function getUploadRootDir()
	{
	 // On retourne le chemin relatif vers l'image pour notre code PHP
	  return __DIR__.'/../../../../web/'.$this->getUploadDir();
	}
	
	public function getWebPath()
	{
	  return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
	}
}

src/OC/PlatformBundle/Controller/AdvertController.php
<?php
// src/OC/PlatformBundle/Controller/AdvertController.php

namespace OC\PlatformBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use OC\PlatformBundle\Entity\Advert;
use OC\PlatformBundle\Form\AdvertType;
use OC\PlatformBundle\Form\AdvertEditType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\Response;

class AdvertController extends Controller
{
  public function indexAction($page)
  {
    if ($page < 1) {
      throw $this->createNotFoundException("La page ".$page." n'existe pas.");
    }

    // Ici je fixe le nombre d'annonces par page à 3
    // Mais bien sûr il faudrait utiliser un paramètre, et y accéder via $this->container->getParameter('nb_per_page')
	$nbPerPage = 3;
	// On récupère notre objet Paginator
    $listAdverts = $this->getDoctrine()
      ->getManager()
      ->getRepository('OCPlatformBundle:Advert')
      ->getAdverts($page, $nbPerPage)
    ;
	
	// On calcule le nombre total de page grâce au count($listAdverts) qui retourne le nombre total d'annonces
	$nbPages = ceil(count($listAdverts)/$nbPerPage);
	
	// Si la page n'existe pas, on retourne une 404
	if($page > $nbPages) {
	  throw $this->createNotFoundException("La page ".$page." n'existe pas."); 
	}
	
    // On donne toutes les informations à la vue
    return $this->render('OCPlatformBundle:Advert:index.html.twig', array(
      'listAdverts' => $listAdverts,
	  'nbPages'     => $nbPages,
	  'page'        => $page
    ));
  }

  public function viewAction($id)
  {
    // On récupère l'EntityManager
    $em = $this->getDoctrine()->getManager();

    // Pour récupérer une annonce unique : on utilise find()
    $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

    // On vérifie que l'annonce avec cet id existe bien
    if ($advert === null) {
      throw $this->createNotFoundException("L'annonce d'id ".$id." n'existe pas.");
    }

    // On récupère la liste des advertSkill pour l'annonce $advert
    $listAdvertSkills = $em->getRepository('OCPlatformBundle:AdvertSkill')->findByAdvert($advert);
 
     // On récupère la liste des candidatures de cette annonce
    $listApplications = $em
      ->getRepository('OCPlatformBundle:Application')
      ->findBy(array('advert' => $advert))
    ;

 
    // Puis modifiez la ligne du render comme ceci, pour prendre en compte les variables :
    return $this->render('OCPlatformBundle:Advert:view.html.twig', array(
      'advert'           => $advert,
      'listAdvertSkills' => $listAdvertSkills,
	  'listApplications' => $listApplications,
    ));
  }
  /**
  * @Security("has_role('ROLE_USER')")
  */
  public function addAction(Request $request)
  {
    // On crée un objet Advert
	$advert = new Advert();
	// Version courte: $form = $this->createForm(new AdvertType(), $advert).
	$form = $this->get('form.factory')->create(new AdvertType(), $advert);
	  
	// On fait le lien Requête <-> Formulaire
    // À partir de maintenant, la variable $advert contient les valeurs entrées dans le formulaire par le visiteur
	// On vérifie que les valeurs entrées sont correctes
    // (Nous verrons la validation des objets en détail dans le prochain chapitre)
	if($form->handleRequest($request)->isValid()) {
	 	 
	 // On l'enregistre notre objet $advert dans la base de données, par exemple
	  $em = $this->getDoctrine()->getManager();
	  $em->persist($advert);
	  $em->flush();
	  
	  $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');
	  
	  // On redirige vers la page de visualisation de l'annonce nouvellement crée
	  return $this->redirect($this->generateUrl('oc_platform_view', array('id' => $advert->getId())));
	  
	  }
		
	// À ce stade, le formulaire n'est pas valide car :
    // - Soit la requête est de type GET, donc le visiteur vient d'arriver sur la page et veut voir le formulaire
    // - Soit la requête est de type POST, mais le formulaire contient des valeurs invalides, donc on l'affiche de nouveau
      return $this->render('OCPlatformBundle:Advert:add.html.twig', array(
        'form' => $form->createView(),
      ));
	}

  public function editAction($id, Request $request)
  {
    // On récupère l'EntityManager
    $em = $this->getDoctrine()->getManager();

    // On récupère l'entité correspondant à l'id $id
    $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);
	
	// Si l'annonce n'existe pas, on affiche une erreur 404
    if ($advert == null) {
      throw $this->createNotFoundException("L'annonce d'id ".$id." n'existe pas.");
    }

    // Ici, on s'occupera de la création et de la gestion du formulaire
	$form = $this->createForm(new AdvertEditType(), $advert);
		
    	
	if($form->handleRequest($request)->isValid()) {
	 // On l'enregistre notre objet $advert dans la base de données, par exemple
	  $em->flush();	 
	  
	  $request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée.');
	    
	  // On redirige vers la page de visualisation de l'annonce nouvellement crée
	  return $this->redirect($this->generateUrl('oc_platform_view', array('id' => $advert->getId())));
	}
	
	return $this->render('OCPlatformBundle:Advert:edit.html.twig', array(
      'advert' => $advert,
	  'form' => $form->createView()
    ));
  }

  public function deleteAction($id, Request $request)
  {
    // On récupère l'EntityManager
    $em = $this->getDoctrine()->getManager();

    // On récupère l'entité correspondant à l'id $id
    $advert = $em->getRepository('OCPlatformBundle:Advert')->find($id);

    // Si l'annonce n'existe pas, on affiche une erreur 404
    if ($advert == null) {
      throw $this->createNotFoundException("L'annonce d'id ".$id." n'existe pas.");
    }
	
	// On crée un formulaire vide, qui ne contiendra que le champ CSRF
    // Cela permet de protéger la suppression d'annonce contre cette faille
	$form = $this->createFormBuilder()->getForm();
	

    if ($form->handleRequest($request)->isValid()) {
      $em->remove($advert);
	  $em->flush();
	  
      $request->getSession()->getFlashBag()->add('info', 'Annonce bien supprimée.');

      // Puis on redirige vers l'accueil
      return $this->redirect($this->generateUrl('oc_platform_home'));
    }

    // Si la requête est en GET, on affiche une page de confirmation avant de delete
    return $this->render('OCPlatformBundle:Advert:delete.html.twig', array(
      'advert' => $advert,
	  'form'   => $form->createView()
    ));
  }

  public function menuAction($limit = 3)
  {
    $listAdverts = $this->getDoctrine()
      ->getManager()
      ->getRepository('OCPlatformBundle:Advert')
      ->findBy(
        array(),                 // Pas de critère
        array('date' => 'desc'), // On trie par date décroissante
        $limit,                  // On sélectionne $limit annonces
        0                        // À partir du premier
    );

    return $this->render('OCPlatformBundle:Advert:menu.html.twig', array(
      'listAdverts' => $listAdverts
    ));
  }
  
  public function createAction() {
    
	$advert = new Advert();
    $advert->setTitle('Mission pour Commercial.');
    $advert->setAuthor('Martial');
    $advert->setContent("Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat…");
	 
	$em = $this->getDoctrine()->getManager();
	$em->persist($advert);
	$em->flush();
	
	return $this->redirect($this->generateUrl('oc_platform_view', array('id' => $advert->getId())));

	}

  public function translationAction($name)
  {
    return $this->render('OCPlatformBundle:Advert:translation.html.twig', array(
      'name' => $name
    ));
  }

  /**
  * @ParamConverter("json")
  */
  public function ParamConverterAction($json)
  {
    return new Response(print_r($json, true));
  }

}	
	

src/OC/PlatformBundle/Resources/views/Advert/add.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/add.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Ajouter une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Ajouter une annonce</h2>

  {{ include("OCPlatformBundle:Advert:form.html.twig") }}

  <p>
    Vous ajoutez une annonce , merci de publier dans
    l'esprit générale des annonces déjà publiée.
  </p>

  <p>
    <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la liste
    </a>
  </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/delete.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Supprimer une annonce</h2>

  <p>
    Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
  </p>

  {# On met l'id de l'annonce dans la route de l'action du formulaire #}
  <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
    <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
    {# Ici j'ai écrit le bouton de soumission à la main #}
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {# Ceci va générer le champ CSRF #}
    {{ form_rest(form) }}
  </form>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/edit.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Modifier une annonce</h2>

  {{ include("OCPlatformBundle:Advert:form.html.twig") }}

  <p>
    Vous éditez une annonce déjà existante, merci de ne pas changer
    l'esprit générale de l'annonce déjà publiée.
  </p>
  
  <p>
    <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
  </p>

{% endblock %}

src/OC/PlatformBundle/Resources/views/Advert/form.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/form.html.twig #}


<h3>Formulaire d'annonce</h3>

<div class="well">
  {{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}

    {# Les erreurs générales du formulaire. #}
    {{ form_errors(form) }}

    <div class="form-group">
      {# Génération du label. #}
      {{ form_label(form.title, "Titre de l'annonce", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}

      {# Affichage des erreurs pour ce champ précis. #}
      {{ form_errors(form.title) }}

      <div class="col-sm-4">
        {# Génération de l'input. #}
        {{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
      </div>
    </div>

    {# Idem pour un autre champ. #}
    <div class="form-group">
      {{ form_label(form.content, "Contenu de l'annonce", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
      {{ form_errors(form.content) }}
      <div class="col-sm-4">
        {{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
      </div>
    </div>
	
	{% if form_date is defined %}
	<div class="form-group">
      {{ form_label(form.date, "Date de l'annonce", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
      {{ form_errors(form.date) }}
      <div class="col-sm-4">
        {{ form_widget(form.date, {'attr': {'class': 'form-control'}}) }}
      </div>
    </div>
	{% endif %}
	
	<div class="form-group">
      {{ form_label(form.author, "Auteur de l'annonce", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
      {{ form_errors(form.author) }}
      <div class="col-sm-4">
        {{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}
      </div>
    </div>
	
	{% if form.published is defined %}
	<div class="form-group">
      {{ form_label(form.published, "Publication de l'annonce", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
      {{ form_errors(form.published) }}
      <div class="col-sm-4">
        {{ form_widget(form.published, {'attr': {'class': 'form-control'}}) }}
      </div>
    </div>
	{% endif %}

  
  {# Génération automatique des champs pas encore écrits.
     Dans cet exemple, ce serait le champ CSRF (géré automatiquement par Symfony !)
     et tous les champs cachés (type « hidden »). #}
  {{ form_rest(form) }}
  
  {# Pour le bouton, pas de label ni d'erreur, on affiche juste le widget #}
  {{ form_widget(form.valider, {'attr': {'class': 'btn btn-primary'}}) }}
  
  {# Fermeture de la balise <form> du formulaire HTML #}
  {{ form_end(form) }}
</div>

{# On charge la bibliothèque jQuery. Ici, je la prends depuis le CDN google mais si vous l'avez en local, changez  simplement l'adresse. #}

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

{# Voici le script en question : #}
<script type="text/javascript">
  $(document).ready(function() {
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#oc_platformbundle_advert_categories');

    // On ajoute un lien pour ajouter une nouvelle catégorie
    var $addLink = $('<a href="#" id="add_category" class="btn btn-default">Ajouter une catégorie</a>');
    $container.append($addLink);

    // On ajoute un nouveau champ à chaque clic sur le lien d'ajout.
    $addLink.click(function(e) {
      addCategory($container);
      e.preventDefault(); // évite qu'un # apparaisse dans l'URL
      return false;
    });

    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;

    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvelle annonce par exemple).
    if (index == 0) {
      addCategory($container);
    } else {
      // Pour chaque catégorie déjà existante, on ajoute un lien de suppression
      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    }

    // La fonction qui ajoute un formulaire Categorie
    function addCategory($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var $prototype = $($container.attr('data-prototype').replace(/__name__label__/g, 'Catégorie n°' + (index+1))
          .replace(/__name__/g, index));

      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);

      // On ajoute le prototype modifié à la fin de la balise <div>
      $container.append($prototype);

      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }

    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

      // Ajout du lien
      $prototype.append($deleteLink);

      // Ajout du listener sur le clic du lien
      $deleteLink.click(function(e) {
        $prototype.remove();
        e.preventDefault(); // évite qu'un # apparaisse dans l'URL
        return false;
      });
    }
  });
</script>

src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/menu.html.twig #}

{# Ce template n'hérite de personne,
   tout comme le template inclus avec {{ include() }}. #}

<ul class="nav nav-pills nav-stacked">
  {% for advert in listAdverts %}
    <li>
      <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
        {{ advert.title }}
      </a>
    </li>
  {% endfor %}
</ul>

src/OC/PlatformBundle/Resources/views/Advert/translation.html.twig
{# src/OC/PlatformBundle/Resources/views/Advert/translation.html.twig #}

<html>
  <body>
    {{ 'Hello'|trans }} {{ name }} {{ 'Are you ok ?'|trans }}
  </body>
</html>

src/OC/PlatformBundle/Resources/views/Advert/view.html.twig
{# src/OC/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "OCPlatformBundle::layout.html.twig" %}

{% block title %}
  Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  {# On verifie qu'une imge soit bien associée à l'annonce #}
  {% if advert.image is not null %}
    <img 
	  src="{{ asset(advert.image.webPath) }}" 
	  alt="{{ advert.image.alt }}" style="float:left; width:25% ">
  {% endif %}

  <h2>{{ advert.title }}</h2>
  <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

  <div class="well">
    {{ advert.content }}
  </div>
  
  {% if not advert.categories.empty %}
  <h3> Liste des catégories </h3>
  <p>
    Cette annonce est parue dans les catégories suivantes :
	{% for category in advert.categories %}
	  {{category.name}}{% if not loop.last %}, {% endif %}
	{% endfor %}
  </p>
  {% endif %}
  
  <h3> Listes des compétences </h3>
  {% if listAdvertSkills|length > 0 %}
  <div>
    Cette annonce requiert les compétences suivantes :
    <ul>
      {% for advertSkill in listAdvertSkills %}
        <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
      {% endfor %}
    </ul>
  </div>
{% endif %}
  
  <h3> Listes des candidatures </h3>
  <ul>
    {% for application in listApplications %}
      <li>
        par {{ application.author }} : {{application.content}}, 
        le {{ application.date|date('d/m/Y') }}
      </li>
    {% else %}
      <li>Pas (encore !) de candidatures </li>
    {% endfor %}
  </ul>

  <p>
    <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la liste
    </a>
    <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-edit"></i>
      Modifier l'annonce
    </a>
    <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
      <i class="glyphicon glyphicon-trash"></i>
      Supprimer l'annonce
    </a>
  </p>

{% endblock %}